#!/usr/bin/env php
<?php

passthru('git checkout master');

$branches = (function (): array {
    $raw = `git branch`;
    $data = array_filter(array_map(function (string $branch): string {
        return trim(str_replace('*', '', $branch));
    }, explode(PHP_EOL, $raw)));

    return $data;
})();

foreach ($branches as $branch) {
    if ($branch === 'master') {
        continue;
    }

    passthru("git checkout {$branch}");

    passthru("git merge master", $exitCode);
    if ($exitCode !== 0) {
        echo "Failed to merge branch 'master' to '{$branch}'";
        exit(1);
    }
}

passthru('git checkout master');
