#!/usr/bin/env php
<?php

$isBaseBranch = function (string $branchName) {
    $regex = '@^v[0-9]+\.[0-9]+\.[0-9]+$@';
    return preg_match($regex, $branchName);
};

$branches = (function (): array {
    $raw = `git branch`;
    $data = array_filter(array_map(function (string $branch): string {
        return trim(str_replace('*', '', $branch));
    }, explode(PHP_EOL, $raw)));

    return $data;
})();

foreach ($branches as $branch) {
    if ($branch === 'master') {
        continue;
    }

    if ($isBaseBranch($branch)) {
        $mergeBranch = 'master';
    } else {
        $mergeBranch = preg_replace('@-v[0-9]+.[0-9]+@', '', $branch);
    }

    passthru("git checkout {$branch}");

    passthru("git merge {$mergeBranch}", $exitCode);
    if ($exitCode !== 0) {
        echo "Failed to merge branch '{$mergeBranch}' to '{$branch}'";
        exit(1);
    }
}

passthru('git checkout master');
