#!/usr/bin/env php
<?php

require_once __DIR__ . '/_common.php';

trackAllBranches();

$push = isset($argv[1]) && $argv[1] === '--push';

$branches = (function (): array {
    $raw = `git branch`;
    $data = array_filter(array_map(function (string $branch): string {
        return trim(str_replace('*', '', $branch));
    }, explode(PHP_EOL, $raw)));

    return $data;
})();

natsort($branches);

unset($branches[array_search('master', $branches)]);

$map = [];

foreach ($branches as $branch) {
    $version = substr($branch, 1);
    $baseVersion = preg_replace('@(\d+\.\d+)\.\d+@', '$1', $version);
    if (!isset($map[$baseVersion])) {
        $map[$baseVersion] = [];
    }

    $map[$baseVersion][$version] = $branch;
    $map[$baseVersion][$baseVersion] = $branch;
}

foreach ($map as $baseVersion => $versions) {
    foreach ($versions as $version => $branch) {
        passthru("git checkout {$branch}", $exitCode);
        passthru("docker build -t rikudousage/qt-static:{$version} .");
        if ($push) {
            passthru("docker push rikudousage/qt-static:{$version}");
        }
    }
}
