#!/usr/bin/env php
<?php

chdir(__DIR__);

$push = in_array('--push', $argv);

$versions = [
    '16.04' => 'xenial',
    '18.04' => 'bionic',
    '20.04' => 'focal',
];

$i = 1;
foreach ($versions as $version => $codename) {
    $command = 'docker build --build-arg VERSION=%s --build-arg CODENAME=%s \\
     -t rikudousage/qt-static-base:%s .';
    passthru(sprintf($command, $version, $codename, $version));
    if ($push) {
        passthru("docker push rikudousage/qt-static-base:{$version}");
    }

    if ($i === count($versions)) {
        passthru(sprintf($command, $version, $codename, 'latest'));
        if ($push) {
            passthru('docker push rikudousage/qt-static-base:latest');
        }
    }

    ++$i;
}
