#!/usr/bin/env php
<?php

chdir(__DIR__);

$push = in_array('--push', $argv);

$versions = [
    '16.04' => 'xenial',
    '18.04' => 'bionic',
];

foreach ($versions as $version => $codename) {
    passthru("docker build --build-arg VERSION={$version} --build-arg CODENAME={$codename} \\
     -t rikudousage/qt-static-base:{$version} .");
}

if ($push) {
    foreach ($versions as $version => $codename) {
        passthru("docker push rikudousage/qt-static-base:{$version}");
    }
}
