name: Build Image
on:
  push:
    branches:
      - 'v5.15.*' # todo replace once tested
#    paths:
#      - 'Dockerfile' # todo trigger only on dockerfile change once tested

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_ACCESS_KEY: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    steps:
      - name: Docker Login
        run: echo $DOCKER_ACCESS_KEY | docker login --username rikudousage --password-stdin
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Build
        run: cd scripts && ./build ${GITHUB_REF##*/} --push --no-pull